# from rechtspraak_extractor import rechtspraak
# from rechtspraak_extractor import rechtspraak_metadata
from rechtspraak_extractor.rechtspraak import get_rechtspraak
from rechtspraak_extractor.rechtspraak_metadata import get_rechtspraak_metadata
